library(readxl)
library(lubridate)
library(dplyr)
library(stringr)
library(xlsx)

all <- read_excel("C:/Users/janecheng/Desktop/INF_Raw_Data.xlsx")

INF_nestle <- dat %>% filter(enterprise=="nestle")

INF_nestle_FB <- INF_nestle %>% filter(grepl("Face",INF_nestle$source)==TRUE)
write.csv(INF_nestle_FB,"C:/Users/janecheng/Desktop/INF/monthly_analysis/INF_FB_nestle.csv")

INF_nestle_blog <- INF_nestle %>% filter(source=="blog")
write.csv(INF_nestle_blog,"C:/Users/janecheng/Desktop/INF/monthly_analysis/INF_blog_nestle.csv")

INF_nestle_news <- INF_nestle %>% filter(source=="news")
write.csv(INF_nestle_news,"C:/Users/janecheng/Desktop/INF/monthly_analysis/INF_news_nestle.csv")

INF_nestle_Forum <- INF_nestle %>% filter(source=="forum")
INF_nestle_Forum2 <- INF_nestle %>% filter(grepl("PTT",INF_nestle$source_web)==TRUE)
INF_nestle_Forum_all <- rbind(INF_nestle_Forum,INF_nestle_Forum2)
write.csv(INF_nestle_blog,"C:/Users/janecheng/Desktop/INF/monthly_analysis/INF_blog_nestle.csv")

INF_whyth_Forum <-惠氏 %>% filter(來源=="forum")
write.csv(INF_whyth_Forum,"C:/Users/janecheng/Desktop/INF/monthly_analysis/INF_Forum_wyeth.csv")

data$塞奶 <- ifelse(grepl("塞奶|石頭奶|乳腺炎|乳房水腫|小白|乳腺",data$content),1,0)
data$發奶 <- ifelse(grepl("發奶|媽媽茶|卵凝脂",data$content),1,0)
data$營養成分 <- ifelse(grepl("葉酸|維他命|DHA|凍晶鐵|營養|補充錠|血紅素鐵|鐵劑|貝鈣|鈣片|肌醇|藻油|魚油|蛋白|益生菌|血紅素|vita|beta|胡蘿蔔|omega 3|elevit|生物素|鎖養層|dha|凝血力",data$content),1,0)
data$初期 <- ifelse(grepl("初期|剛懷孕",data$content),1,0)
data$中期 <- ifelse(grepl("中期",data$content),1,0)
data$後期 <- ifelse(grepl("後期",data$content),1,0)
data$藥局 <- ifelse(grepl("藥局|藥師",data$content),1,0)
data$劑量 <- ifelse(grepl("劑量|含量",data$content),1,0)
data$天然 <- ifelse(grepl("天然",data$content),1,0)
data$口味 <- ifelse(grepl("酸|甜|苦|優格|草莓|葡萄|香草|怪味|味道|口味",data$content),1,0)
data$好吞與否 <- ifelse(grepl("好吞|大顆|小顆|大小|難吞",data$content),1,0)
data$醫生 <- ifelse(grepl("醫生|醫師|醫院|小兒科",data$content),1,0)
data$備孕 <- ifelse(grepl("備孕",data$content),1,0)
data$月子 <- ifelse(grepl("月子",data$content),1,0)
data$牛奶 <- ifelse(grepl("牛奶",data$content),1,0)
data$試吃 <- ifelse(grepl("試吃|開封|開罐|試用包",data$content),1,0)
data$追奶 <- ifelse(grepl("追奶",data$content),1,0)
data$過期 <- ifelse(grepl("過期",data$content),1,0)
data$媽媽包 <- ifelse(grepl("媽媽包|贈品|婦幼展",data$content),1,0)
data$方便 <- ifelse(grepl("方便|好帶",data$content),1,0)
data$便祕 <- ifelse(grepl("便秘",data$content),1,0)
data$價格 <- ifelse(grepl("價格|貴|便宜|價錢|價位",data$content),1,0)
write.csv(data,"C:/Users/janecheng/Desktop/INF/monthly_analysis/Rawdata/dimension_only_in_content_done.csv")


data$塞奶 <- ifelse(grepl("塞奶|石頭奶|乳腺炎|乳房水腫|小白|乳腺",data$tittle),1,0)
data$發奶 <- ifelse(grepl("發奶|媽媽茶|卵凝脂",data$tittle),1,0)
data$營養成分 <- ifelse(grepl("葉酸|維他命|DHA|凍晶鐵|營養|補充錠|血紅素鐵|鐵劑|貝鈣|鈣片|肌醇|藻油|魚油|蛋白|益生菌|血紅素|vita|beta|胡蘿蔔|omega 3|elevit|生物素|鎖養層|dha|凝血力",data$tittle),1,0)
data$初期 <- ifelse(grepl("初期|剛懷孕",data$tittle),1,0)
data$中期 <- ifelse(grepl("中期",data$tittle),1,0)
data$後期 <- ifelse(grepl("後期",data$tittle),1,0)
data$藥局 <- ifelse(grepl("藥局|藥師",data$tittle),1,0)
data$劑量 <- ifelse(grepl("劑量|含量",data$tittle),1,0)
data$天然 <- ifelse(grepl("天然",data$tittle),1,0)
data$口味 <- ifelse(grepl("酸|甜|苦|優格|草莓|葡萄|香草|怪味|味道|口味",data$tittle),1,0)
data$好吞與否 <- ifelse(grepl("好吞|大顆|小顆|大小|難吞",data$tittle),1,0)
data$醫生 <- ifelse(grepl("醫生|醫師|醫院|小兒科",data$tittle),1,0)
data$備孕 <- ifelse(grepl("備孕",data$tittle),1,0)
data$月子 <- ifelse(grepl("月子",data$tittle),1,0)
data$牛奶 <- ifelse(grepl("牛奶",data$tittle),1,0)
data$試吃 <- ifelse(grepl("試吃|開封|開罐|試用包",data$tittle),1,0)
data$追奶 <- ifelse(grepl("追奶",data$tittle),1,0)
data$過期 <- ifelse(grepl("過期",data$tittle),1,0)
data$媽媽包 <- ifelse(grepl("媽媽包|贈品|婦幼展",data$tittle),1,0)
data$方便 <- ifelse(grepl("方便|好帶",data$tittle),1,0)
data$便祕 <- ifelse(grepl("便秘",data$tittle),1,0)
data$價格 <- ifelse(grepl("價格|貴|便宜|價錢|價位",data$tittle),1,0)

write.csv(data,"C:/Users/janecheng/Desktop/INF/monthly_analysis/Rawdata/dimension_only_in_title_done.csv")